config/routes.rb
Rails.application.routes.draw do
	root 'welcome#home'

	resources :users
	resources :services
	resources :menus
	resources :pages
	resources :sessions,	only: [ :new, :create, :destroy ]

	match '/signin',	to: 'sessions#new',		via: 'get'
	match '/signout',	to: 'sessions#destroy',	via: 'delete'
	match '/signup',	to: 'users#new',		via: 'get'
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

	before_save { email.downcase! }
	before_create :create_remember_token

	validates :name, presence: true, length: { in: 3..50 }
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
					  uniqueness: { case_sensitive: false }

	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true

	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	private

		def create_remember_token
			self.remember_token = User.encrypt(User.new_remember_token)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_cms_mode #, only: [ :index, :show, :new, :edit ]
  before_action :get_cms_menu
  
  before_action :signed_in_user,  only: [ :edit,    :update,  :index ]
  # before_action :correct_user,    only: [ :edit,    :update ]
  # before_action :auth_user,       only: [ :new,     :create ]
  # before_action :admin_user,      only: [ :destroy, :index ]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      flash[:success] = 'User created'
      unless signed_in?
        sign_in @user
        redirect_to @user 
      else
        redirect_to users_path 
      end
    else
      flash.now[:error] = "User don't created"
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes user_params
      flash[:success] = 'User updated'
      redirect_to @user
    else
      flash.now[:error] = "User don't updated"
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User was removed.'
    redirect_to users_path
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages',	object: f.object %>
<%= f.label				:name %>
<%= f.text_field		:name %>
<%= f.label				:email %>
<%= f.email_field		:email %>
<%= f.label				:password %>
<%= f.password_field	:password %>
<%= f.label				:password_confirmation %>
<%= f.password_field	:password_confirmation %>

app/views/users/_user.html.erb
<tr>
	<td><%= user.id %></td>
	<td><%= user.name %></td>
	<td><%= link_to user.email, "mailto:#{user.email}" %></td>
	<td><%= link_to 'Просмотр', user %></td>
	<td><%= link_to 'Изменить', edit_user_path(user) %></td>
	<td><%= link_to 'Удалить', user, method: 'delete' unless current_user?(user) %></td>
</tr>

app/views/users/edit.html.erb
<% provide :title, "Изменение #{@user.name}" %>
<section class="block">
	<div class="container">
		<h1><%= "Изменение #{@user.name}" %></h1>
		<div class="form">
			<%= form_for @user, class: 'form' do |f| %>
				<%= render 'fields', f: f %>
				<%= f.submit 'Изменить' %>
			<% end %>
		</div>
	</div>
</section>
			

app/views/users/index.html.erb
<% provide :title, 'Пользователи' %>
<section class="block">
	<div class="container">
		<h1>Пользователи</h1>
		<table class="table">
			<thead>
				<th>#</th>
				<th>Имя</th>
				<th>email</th>
				<th colspan="3">Действия</th>
			</thead>
			<%= render @users %>
		</table>
		<%= link_to 'Создать', new_user_path %>
		<%= will_paginate %>
	</div>
</section>

app/views/users/new.html.erb
<% provide :title, "Регистрация" %>

<section class="block">
	<div class="container">
		<h1>Регистрация</h1>
		<div class="form">
			<%= form_for @user, class: 'form' do |f| %>
				<%= render 'fields', f: f %>
				<%= f.submit 'Вход' %>
			<% end %>
		</div>
	</div>
</section>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<section class="block">
	<div class="container">
		<h1><%= @user.name %></h1>
		<small><%= link_to 'Edit', edit_user_path(@user) %></small>
	</div>
</section>