config/routes.rb
Rails.application.routes.draw do
	root 'welcome#home'

	resources :users
	resources :services
	resources :menus
	resources :pages
	resources :sessions,	only: [ :new, :create, :destroy ]

	match '/signin',	to: 'sessions#new',		via: 'get'
	match '/signout',	to: 'sessions#destroy',	via: 'delete'
	match '/signup',	to: 'users#new',		via: 'get'
end

app/views/pages/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>
<%= f.label :title, 'Заголовок' %>
<%= f.text_field :title %>
<%= f.label :href, 'Адрес' %>
<%= f.text_field :href %>
<%= f.label :enabled, 'Доступность' %>
<%= f.check_box :enabled %>
<%= f.label :meta_title %>
<%= f.text_field :meta_title %>
<%= f.label :meta_desc %>
<%= f.text_field :meta_desc %>
<%= f.label :meta_keywords %>
<%= f.text_field :meta_keywords %>
<%= f.label :body, 'Страница' %>
<%= f.text_area :body %>

app/views/pages/_page.html.erb
<tr>
	<td><%= page.id %></td>
	<td><%= page.title %></td>
	<td><%= page.href %></td>
	<td><%= link_to 'Просмотр', page %></td>
	<td><%= link_to 'Изменить', edit_page_path(page) %></td>
	<td><%= link_to 'Удалить', page, method: 'delete' %></td>
</tr>

app/views/pages/edit.html.erb
<% provide :title, "Изменение #{@page.title}" %>
<section class="block">
	<div class="container">
		<h1>Изменение <%= @page.title %></h1>
		<div class="form form-small">
			<%= form_for @page, class: 'form' do |f| %>
				<%= render 'fields', f: f %>
				<%= f.submit 'Изменить' %>
			<% end %>
		</div>
	</div>
</section>
			

app/views/pages/index.html.erb
<% provide :title, 'Страницы' %>
<section class="block">
	<div class="container">
		<h1>Страницы</h1>
		<table class="table">
			<thead>
				<th>#</th>
				<th>Заголовок</th>
				<th>Путь</th>
				<th colspan="3">Действия</th>
			</thead>
			<%= render @pages %>
		</table>
		<%= link_to 'Создать', new_page_path, class: 'btn' %>
		<%= will_paginate %>
	</div>
</section>

app/views/pages/new.html.erb
<% provide :title, 'Создание страницы' %>
<section class="block">
	<div class="container">
		<h1>Создание страницы</h1>
		<div class="form form-small">
			<%= form_for @page, class: 'form' do |f| -%>
				<%= render 'fields', f: f %>
				<%= f.submit 'Создать' %>
			<% end -%>
		</div>
	</div>
</section>

app/views/pages/show.html.erb
<% provide :title, @page.title %>
<section class="block">
	<div class="container">
		<h1><%= @page.title %></h1>
		<div id="content">
			<%= render inline: @page.body %>
		</div>
	</div>
</section>