config/routes.rb
Rails.application.routes.draw do
	root 'welcome#home'

	resources :users
	resources :services
	resources :menus
	resources :pages
	resources :sessions,	only: [ :new, :create, :destroy ]

	match '/signin',	to: 'sessions#new',		via: 'get'
	match '/signout',	to: 'sessions#destroy',	via: 'delete'
	match '/signup',	to: 'users#new',		via: 'get'
end

app/views/layouts/_adv.html.erb
<!-- Google.Analityc -->
<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

	ga('create', 'UA-57607571-1', 'auto');
	ga('send', 'pageview');
</script>
<!---->
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
	(function (d, w, c) {
	    (w[c] = w[c] || []).push(function() {
	        try {
	            w.yaCounter27456180 = new Ya.Metrika({id:27456180,
	                    clickmap:true,
	                    trackLinks:true,
	                    accurateTrackBounce:true});
	        } catch(e) { }
	    });

	    var n = d.getElementsByTagName("script")[0],
	        s = d.createElement("script"),
	        f = function () { n.parentNode.insertBefore(s, n); };
	    s.type = "text/javascript";
	    s.async = true;
	    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

	    if (w.opera == "[object Opera]") {
	        d.addEventListener("DOMContentLoaded", f, false);
	    } else { f(); }
	})(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="//mc.yandex.ru/watch/27456180" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

app/views/layouts/_cms.html.erb
<header class="layout-header">
	<div class="layout-container">
		<div class="layout-col-2 logo">
			<%= link_to 'CMS', '/' %>
		</div>
		<div class="layout-col-10 nav">
			<nav class="layout-nav">
				<ul>
					<li><%= link_to 'Пользователи',	users_path %></li>
					<li><%= link_to 'Меню',		menus_path %></li>
					<li><%= link_to 'Страницы',	pages_path %></li>
					<li><%= link_to 'Услуги',	services_path %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>
<div class="layout-main">
	<div class="layout-container">
		<%= render 'shared/alerts' %>
		<%= yield %>
	</div>
</div>
<footer class="layout-footer">
	<%= render 'layouts/footer' %>
</footer>

app/views/layouts/_footer.html.erb
<div class="vertical-middle"></div>
<div id="dev_info">
	Создано <a href="http://voove.ru" id="logo_dev">VooVe</a> специально для &copy; ООО "Контр-В" <%= DateTime.now.year %>
</div>
<% unless cms? %>
<ul id="nav_arrows">
	<li><i class="fa fa-chevron-up fa-2x fa-inverse prev"></i></li>
	<li><i class="fa fa-chevron-down fa-2x fa-inverse next"></i></li>
</ul>
<% end %>

app/views/layouts/_header.html.erb
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<title><%= full_title(yield(:title)) %></title>
<%= csrf_meta_tags %>
<meta name="title" content="<%= meta_title %>"/>
<meta name="description" content="<%= meta_desc %>"/>
<meta name="keywords" content="<%= meta_keywords %>"/>
<meta name="viewport" content="width=device-width, user-scalable=no"/>
<meta name='yandex-verification' content='7e68b0bf8d1e7002' />

app/views/layouts/_micro.html.erb
<div id="micro" itemscope itemtype="http://schema.org/Organization">
	<span itemprop="name">ООО "Контр-В"</span>
	<div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
		<span itemprop="streetAddress">Гатчинская, 3а</span>
		<span itemprop="postalCode">188510</span>
		<span itemprop="addressLocality">
			Волосово
		</span>
		<span itemprop="addressCountry">Россия</span>
		<span itemprop="addressRegion">
			Ленинградская область
		</span>
	</div>
	<div itemprop="geo" itemscope itemtype="http://schema.org/geo">
		<span itemprop="latitude">59.4537712</span>
		<span itemprop="longitude">29.4976668</span>
	</div>
	<span itemprop="telephone">+7 921 447-40-30</span>
	<span itemprop="email">contr-v@mail.ru</span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head><%= render 'layouts/header' %></head>
	<body>
		<header>
			<nav id="main_nav">
				<span id="nav_btn" class="fa-stack fa-2x">
					<i class="fa fa-navicon fa-stack-1x fa-inverse"></i>
				</span>
				<div id="logo"><a href="/">Контр-В</a></div>
				<ul class="nav">
					<% @menu.each do |x| %>
						<li><%= link_to x.title, (cms? ? x.href : "##{x.href}") %></li>
					<% end %>
				</ul>
			</nav>
		</header>
		<main id="main">
			<%= yield %>
		</main>
		<section id="wrapper">
			<div class="pattern"></div>
			<% unless cms? %>
			<a id="bgndVideo" class="player mb_YTVPlayer" data-property="{videoURL:'http://www.youtube.com/watch?v=0cQHmNJ4nFE',containment:'body',autoPlay:true, mute:true, startAt:0, opacity:1}" style="display: none; background: none;" title="Contr-V Promo"></a>
			<% end %>
		</section>
		<footer id="footer"><%= render 'layouts/footer' %></footer>
		<%= render 'layouts/micro' unless cms? %>
	</body>
	<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true, async: true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true, async: true %>
	<%= render 'layouts/adv' %>
</html>